// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMX9HE5VDh0AotmXBnG1-vcuaIm0pADBg',
    appId: '1:565753001401:web:457f4da88992185fd93268',
    messagingSenderId: '565753001401',
    projectId: 'poststaskproject',
    authDomain: 'poststaskproject.firebaseapp.com',
    storageBucket: 'poststaskproject.appspot.com',
    measurementId: 'G-02YXJMYX7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbwHYZyapUE_wqMRO-_AxmUD0G8P62qx8',
    appId: '1:565753001401:android:6ae6b388d41e2ebdd93268',
    messagingSenderId: '565753001401',
    projectId: 'poststaskproject',
    storageBucket: 'poststaskproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq-GmZRd9MdOWX-qASpKlr2dPNeclXaQI',
    appId: '1:565753001401:ios:a52c3e7c2311ed38d93268',
    messagingSenderId: '565753001401',
    projectId: 'poststaskproject',
    storageBucket: 'poststaskproject.appspot.com',
    iosBundleId: 'com.example.taskProject',
  );
}
